### ISSUE TITLE
outdated tinyproxy

### ISSUE THREAD

**Issue by rofl0r** [ajoergensen/docker-tinyproxy#2]
i (tinyproxy maintainer) have been getting complaints that your dockerfile doesn't work.
you should probably make it so latest alpine is used which uses the new tinyproxy 1.11.0 release which has dozens of bugfixes. also the SPARE_SERVERS and similar config items are no longer used, simply MAXCLIENTS is required. the new config also defaults to not using any CONNECT_PORTS at all and allow all ports for SSL. the new tinyproxy release also allows logging to stdout (if no syslog or conf file if used), which should simplify things with s6.

**Comment by gingerbeardman** [comment]
This seems to have been fixed as the docker container was updated last week. Should fix your https://github.com/tinyproxy/tinyproxy/issues/413

Docker: https://hub.docker.com/r/ajoergensen/tinyproxy

Doing `tinyproxy -v` in my container shows: `tinyproxy 1.11.0`

> Though strangely this repo has no recent changes.

**Comment by gingerbeardman** [comment]
I just updated my install and can confirm it is tracking the tinyproxy latest, showing 1.11.1 at this time.
